### ISSUE TITLE
Split Anilist/Anichart

### ISSUE THREAD

**Issue by sgoudham** [catppuccin-rfc/userstyles#12]
## Description

The current user-style for Anilist actually contains code to theme Anichart too. For the central userstyles repository, we believe it makes sense to just split it out.

## Acceptance Criteria

- [ ] 2 folders are created: `styles/anilist` & `styles/anichart`
- [ ] The `userstyles.yml` is updated to reflect the above changes

**Comment by nekowinston** [comment]
We've decided against this yesterday, since it shares so much in common & it's the same Brand - we'll deal with this in the yaml schema.
