### ISSUE TITLE
Tidy Up README/CONTRIBUTING

### ISSUE THREAD

**Issue by sgoudham** [catppuccin-rfc/userstyles#13]
## Description

Currently, the README is not up to the Catppuccin Aesthetic™ as it just includes the auto-generated userstyles list. We should include a short description of what this repository is.

We should also flesh out the Contributing section to highlight the process of adding/PR'ing a userstyle into the repository. I'm personally hoping that a well-formatted PR template should do most of the work here.

## Acceptance Criteria 

- [ ] Short description of what the repository is
- [x] Mention to enable `csp-patching` for the Stylus extension
- [ ] Contributing section which highlights how the repository is architected + link to Pull Request template.

**Comment by rubyowo** [comment]
I'd like to note that we always show the csp-patching line anyway regardless
and it'd it better if we just remove it from the yaml and schema rather than setting it to true.
